version: "3.8"

services:
  database:
    image: postgres:16.3
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  api:
    build:
      # context: ~/git/homecontrol-api
      context: https://github.com/2851999/homecontrol-api.git#v0.7.0
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./config/logging.ini:/homecontrol-api/logging.ini
      - ./config:/etc/homecontrol
    # Required for mDNS discovery (Won't work on Windows/WSL)
    network_mode: "host"
    # ports:
    #   - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homecontrol_api.rule=Host(`${HOSTNAME}`) && PathPrefix(`/homecontrol-api`)"
      # Need port here as host networking wont specify so can't use it from above
      - "traefik.http.services.homecontrol_api.loadbalancer.server.port=8000"
      # HTTPS
      - "traefik.http.routers.homecontrol_api.entrypoints=websecure"
      - "traefik.http.routers.homecontrol_api.tls=true"
    depends_on:
      - database

  ui:
    build:
      # context: ~/git/homecontrol-ui
      context: https://github.com/2851999/homecontrol-ui.git#v0.6.1
      dockerfile: Dockerfile.prod
    volumes:
      - ./config/ui.json:/homecontrol-ui/public/config.json
    restart: always
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homecontrol_ui.rule=Host(`${HOSTNAME}`)"
      # Forces name rather than ui_homecontrol
      - "traefik.http.services.homecontrol_ui.loadbalancer.server.port=3000"
      # HTTPS
      - "traefik.http.routers.homecontrol_ui.entrypoints=websecure"
      - "traefik.http.routers.homecontrol_ui.tls=true"
    depends_on:
      - api

  traefik:
    image: traefik:v3.0
    command:
      - "--log.level=INFO"
      - "--accessLog=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Global HTTP to HTTPS redirect
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # HTTPS
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certificates:/etc/certs:ro
    restart: always
    # Will get bad gateway if not using host networking here while also using it above for homecontrol-api
    network_mode: "host"
    # ports:
    #   - "80:80"
    #   - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${HOSTNAME}`) && (PathPrefix(`/dashboard/`) || PathPrefix(`/api`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}"
      # https://stackoverflow.com/questions/58580782/traefik-2-0-port-is-missing-for-internal-dashboard
      - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
      # HTTPS
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
    depends_on:
      - api
      - ui
